### ISSUE TITLE
Identify & Describe Viable Design Patterns

### ISSUE THREAD

**Issue by levantocode** [levantocode/go-engine-ot#3]
# Description

**Design Patterns** provide proven and well thought solutions to common design challenges in a way that improves **Code Quality, Maintainability, and Reusability**.

They also serve as answers to what would otherwise be considered difficult/complex, time-consuming problems.

By having a list of **Viable Design Patterns** (considering the **Map of Core Components** for the Game Engine) with clear and concise documentation centralized in the **Project's Knowledge Base**, the already reduced complexity of developing each component is reduced even further by the existence of a guided reference of each pre-defined high quality solution for each major problem.

The documentation also helps any future collaboration.

# Tasks
- [ ] Identify Viable Design Patterns
- [ ] Create Clear & Concise Documentation for each one to share on the Knowledge Base
- [ ] Map each Design Pattern to the Core Components that they apply
