### ISSUE TITLE
Identify & Document Components of Game Engine Architecture

### ISSUE THREAD

**Issue by levantocode** [levantocode/go-engine-ot#4]
# Description

Although Game Engines vary widely in Architecture details and Implementations, virtually all game engines contain a familiar set of Core Components.

As such, there are many Architectural Components (ACs) that compose a Game Engine Architecture but not all are necessary.
Such Components are the most abstract form of Components and their existence depends upon each of the Game's Scope & Requirements.

Having a list of common ACs and how they are organized, we can begin to relate each component with the game of Tibia to determine which ACs are not necessary, and of those that are, what are their Requirements, as well as potential connections/dependencies with other ACs.

Having this information fleshed out is essential to set a realistic Game Engine Architecture that will guide the decision of Viable Design Patterns to be able to start coding a high quality codebase.

# Tasks
- [ ] Generic List of all Game Engine ACs
- [ ] Relating & Filtering each AC with Tibia's Scope
- [ ] Identifying Core Requirements of each AC
- [ ] Identifying possible Relationships & Dependencies between Selected ACs
