### ISSUE TITLE
Develop Server Status Manager

### ISSUE THREAD

**Issue by levantocode** [levantocode/go-engine-ot#6]
# Description
The Server Status Manager (SSM) coordinates all the state changes related with the sever status,

The SSM will be implemented with 2 Design Patterns:
- State Pattern (Coordinates State Changes)
- Observer Pattern (Receives Events to trigger changes)

# Tasks
- [x] Implement the Observer Pattern
- [ ] Create & Implement the State Pattern
- [ ] Create Tests for each state change

**Comment by levantocode** [comment]
Progress in this feature will halt a bit to reconsider the viability of implementing the State Pattern after gathering the all the requirements for status changes.
