### ISSUE TITLE
Create Basic Account Manager System

### ISSUE THREAD

**Issue by levantocode** [levantocode/go-engine-ot#7]
# Description

The Account Manager System provides the user with a mechanism to perform CRUD Operation about Accounts & Characters.

Obs.: At the moment of this note, the database is not implemented yet as decisions about it are still being evaluated. But this is a good example where Modularization allow for development to continue with ease. By creating a DB Interface, the fact that the DB doesn't exist yet doesn't block the progress of this task.

# Tasks

- [ ] Create Database Interface for CRUD Operations on Accounts & Characters
- [ ] Create CRUD Services for Accounts
- [ ] Create CRUD Services for Characters
